from datetime import datetime
from fpdf import FPDF

BRAND_RED    = (204, 41, 41)
BRAND_BLUE   = (110, 180, 212)
BRAND_YELLOW = (245, 194, 0)
BRAND_GREEN  = (74, 139, 63)
BRAND_DARK   = (30, 30, 30)
BRAND_LIGHT  = (249, 249, 249)
BRAND_MID    = (85, 85, 85)
WHITE        = (255, 255, 255)
LIGHT_GREY   = (240, 240, 240)


class ProgressPDF(FPDF):
    def __init__(self, child_name: str, report_date: str, app_name: str, app_domain: str):
        super().__init__()
        self.child_name = child_name
        self.report_date = report_date
        self.app_name = app_name
        self.app_domain = app_domain
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        self.set_fill_color(*BRAND_RED)
        self.rect(0, 0, 210, 38, 'F')
        self.set_fill_color(*BRAND_YELLOW)
        self.rect(0, 38, 210, 2, 'F')

        self.set_xy(14, 7)
        self.set_text_color(*WHITE)
        self.set_font('Helvetica', 'B', 16)
        self.cell(0, 8, f'{self.app_name} - Progress Report', ln=True)

        self.set_x(14)
        self.set_font('Helvetica', '', 9)
        self.set_text_color(255, 230, 230)
        self.cell(0, 5, f'AI Educational Chatbot  |  {self.app_domain}', ln=True)

        self.set_x(14)
        self.set_font('Helvetica', '', 9)
        self.set_text_color(*WHITE)
        self.cell(0, 5, f'Student: {self.child_name}   |   Report Date: {self.report_date}', ln=True)

        self.set_y(48)
        self.set_text_color(*BRAND_DARK)

    def footer(self):
        self.set_y(-18)
        self.set_fill_color(*LIGHT_GREY)
        self.rect(0, self.get_y() - 2, 210, 20, 'F')
        self.set_font('Helvetica', '', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 8, f'Generated by {self.app_name}  |  {self.report_date}  |  Confidential - For parent/guardian of {self.child_name}', align='C')

    def section_title(self, title: str):
        self.ln(4)
        self.set_font('Helvetica', 'B', 11)
        self.set_text_color(*BRAND_RED)
        self.cell(0, 8, title.upper(), ln=True)
        # Yellow underline
        x, y = self.get_x(), self.get_y()
        self.set_fill_color(*BRAND_YELLOW)
        self.rect(14, y, 182, 1.5, 'F')
        self.ln(5)
        self.set_text_color(*BRAND_DARK)

    def stat_card(self, x: float, y: float, w: float, value: str, label: str, color=None):
        color = color or BRAND_BLUE
        # Card background
        self.set_fill_color(*BRAND_LIGHT)
        self.rect(x, y, w, 22, 'F')
        # Left color stripe
        self.set_fill_color(*color)
        self.rect(x, y, 3, 22, 'F')
        # Value
        self.set_xy(x + 6, y + 3)
        self.set_font('Helvetica', 'B', 18)
        self.set_text_color(*color)
        self.cell(w - 8, 10, str(value))
        # Label
        self.set_xy(x + 6, y + 13)
        self.set_font('Helvetica', '', 7)
        self.set_text_color(*BRAND_MID)
        self.cell(w - 8, 6, label.upper())
        self.set_text_color(*BRAND_DARK)


def generate_progress_pdf(
    child_data: dict,
    progress_data: dict,
    badges: list,
    app_name: str = "MamaBird & Chirpy",
    app_domain: str = "threebabybirdies.com",
) -> bytes:
    child_name = child_data.get("child_name", "Student")
    age = child_data.get("age")
    grade = child_data.get("grade")
    report_date = datetime.utcnow().strftime("%B %d, %Y")
    total_sessions = child_data.get("total_sessions", 0)
    streak_days = child_data.get("streak_days", 0)

    total_correct = sum(v.get("correct", 0) for v in progress_data.values())
    total_questions = sum(v.get("total", 0) for v in progress_data.values())
    overall_accuracy = round(total_correct / total_questions * 100, 1) if total_questions else 0.0

    age_grade_parts = []
    if age:
        age_grade_parts.append(f"Age {age}")
    if grade:
        grade_str = grade if str(grade).lower().startswith("grade") else f"Grade {grade}"
        age_grade_parts.append(grade_str)
    age_grade_str = "  |  " + "  ·  ".join(age_grade_parts) if age_grade_parts else ""

    pdf = ProgressPDF(child_name=child_name + age_grade_str, report_date=report_date, app_name=app_name, app_domain=app_domain)
    pdf.add_page()

    # ── Overall Summary ──────────────────────────────────────────
    pdf.section_title("Overall Summary")

    card_y = pdf.get_y()
    card_w = 41.5
    gap = 3.5
    x_start = 14
    cards = [
        (f"{overall_accuracy}%", "Overall Accuracy", BRAND_BLUE),
        (str(total_sessions),    "Total Sessions",   BRAND_RED),
        (str(total_questions),   "Questions Answered", BRAND_GREEN),
        (str(streak_days),       "Day Streak",       (245, 140, 0)),
    ]
    for i, (val, lbl, col) in enumerate(cards):
        pdf.stat_card(x_start + i * (card_w + gap), card_y, card_w, val, lbl, col)

    pdf.set_y(card_y + 28)

    # ── Progress by Subject ──────────────────────────────────────
    pdf.section_title("Progress by Subject")

    if not progress_data:
        pdf.set_font('Helvetica', 'I', 10)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 8, "No subject data recorded yet.", ln=True)
        pdf.set_text_color(*BRAND_DARK)
    else:
        # Table header
        col_widths = [60, 40, 36, 46]
        headers = ["Subject", "Correct / Total", "Accuracy", "Progress"]
        pdf.set_fill_color(*BRAND_BLUE)
        pdf.set_text_color(*WHITE)
        pdf.set_font('Helvetica', 'B', 9)
        for w, h in zip(col_widths, headers):
            pdf.cell(w, 9, h, fill=True, border=0)
        pdf.ln()

        pdf.set_font('Helvetica', '', 10)
        row_fill = False
        for subject, vals in sorted(progress_data.items()):
            correct = vals.get("correct", 0)
            total = vals.get("total", 0)
            acc = vals.get("accuracy_pct", 0.0)

            if acc >= 80:
                acc_color = BRAND_GREEN
            elif acc >= 50:
                acc_color = (180, 140, 0)
            else:
                acc_color = BRAND_RED

            row_y = pdf.get_y()
            if row_fill:
                pdf.set_fill_color(*BRAND_LIGHT)
                pdf.rect(14, row_y, 182, 10, 'F')

            pdf.set_text_color(*BRAND_DARK)
            pdf.set_font('Helvetica', 'B', 10)
            pdf.cell(col_widths[0], 10, subject.title())

            pdf.set_font('Helvetica', '', 10)
            pdf.cell(col_widths[1], 10, f"{correct} / {total}")

            pdf.set_text_color(*acc_color)
            pdf.set_font('Helvetica', 'B', 10)
            pdf.cell(col_widths[2], 10, f"{acc}%")

            # Progress bar
            bar_x = pdf.get_x()
            bar_y = row_y + 3
            pdf.set_fill_color(220, 220, 220)
            pdf.rect(bar_x, bar_y, 44, 4, 'F')
            fill_w = min(int(acc * 44 / 100), 44)
            pdf.set_fill_color(*BRAND_BLUE)
            if fill_w > 0:
                pdf.rect(bar_x, bar_y, fill_w, 4, 'F')
            pdf.ln(10)
            pdf.set_text_color(*BRAND_DARK)
            row_fill = not row_fill

    # ── Badges Earned ──────────────────────────────────────────
    pdf.section_title("Badges Earned")

    if not badges:
        pdf.set_font('Helvetica', 'I', 10)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 8, "No badges earned yet - keep learning!", ln=True)
        pdf.set_text_color(*BRAND_DARK)
    else:
        badge_w = 58
        badge_h = 16
        gap_x = 3
        badges_per_row = 3
        page_bottom = pdf.h - 25  # 25 mm from bottom keeps clear of footer

        # Disable auto page break — we handle page breaks manually so the
        # absolute-coordinate rect() calls don't get split mid-row.
        pdf.set_auto_page_break(False)
        badge_y = pdf.get_y()

        for i, b in enumerate(badges):
            name = b.get("badge_name", "Badge")
            earned = b.get("earned_at", "")
            date_str = earned[:10] if earned else ""

            col = i % badges_per_row

            if col == 0 and i > 0:
                badge_y += badge_h + 3
                if badge_y + badge_h > page_bottom:
                    pdf.add_page()
                    badge_y = 20

            bx = 14 + col * (badge_w + gap_x)

            pdf.set_fill_color(*BRAND_LIGHT)
            pdf.rect(bx, badge_y, badge_w, badge_h, 'F')
            pdf.set_draw_color(*BRAND_YELLOW)
            pdf.rect(bx, badge_y, badge_w, badge_h, 'D')

            pdf.set_xy(bx + 3, badge_y + 3)
            pdf.set_font('Helvetica', 'B', 9)
            pdf.set_text_color(*BRAND_DARK)
            pdf.cell(badge_w - 6, 5, name[:22], ln=False)

            if date_str:
                pdf.set_xy(bx + 3, badge_y + 9)
                pdf.set_font('Helvetica', '', 7)
                pdf.set_text_color(150, 150, 150)
                pdf.cell(badge_w - 6, 4, date_str)

            pdf.set_text_color(*BRAND_DARK)

        pdf.set_auto_page_break(True, margin=20)
        pdf.set_y(badge_y + badge_h + 8)

    return bytes(pdf.output())


class ClassroomPDF(FPDF):
    def __init__(self, class_name: str, report_date: str, app_name: str, app_domain: str):
        super().__init__()
        self.class_name = class_name
        self.report_date = report_date
        self.app_name = app_name
        self.app_domain = app_domain
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        self.set_fill_color(*BRAND_RED)
        self.rect(0, 0, 210, 38, 'F')
        self.set_fill_color(*BRAND_YELLOW)
        self.rect(0, 38, 210, 2, 'F')

        self.set_xy(14, 7)
        self.set_text_color(*WHITE)
        self.set_font('Helvetica', 'B', 16)
        self.cell(0, 8, f'{self.app_name} - Class Progress Report', ln=True)

        self.set_x(14)
        self.set_font('Helvetica', '', 9)
        self.set_text_color(255, 230, 230)
        self.cell(0, 5, f'AI Educational Chatbot  |  {self.app_domain}', ln=True)

        self.set_x(14)
        self.set_font('Helvetica', '', 9)
        self.set_text_color(*WHITE)
        self.cell(0, 5, f'Class: {self.class_name}   |   Report Date: {self.report_date}', ln=True)

        self.set_y(48)
        self.set_text_color(*BRAND_DARK)

    def footer(self):
        self.set_y(-18)
        self.set_fill_color(*LIGHT_GREY)
        self.rect(0, self.get_y() - 2, 210, 20, 'F')
        self.set_font('Helvetica', '', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 8, f'Generated by {self.app_name}  |  {self.report_date}  |  Confidential - For {self.class_name}', align='C')

    def section_title(self, title: str):
        self.ln(4)
        self.set_font('Helvetica', 'B', 11)
        self.set_text_color(*BRAND_RED)
        self.cell(0, 8, title.upper(), ln=True)
        x, y = self.get_x(), self.get_y()
        self.set_fill_color(*BRAND_YELLOW)
        self.rect(14, y, 182, 1.5, 'F')
        self.ln(5)
        self.set_text_color(*BRAND_DARK)

    def stat_card(self, x: float, y: float, w: float, value: str, label: str, color=None):
        color = color or BRAND_BLUE
        self.set_fill_color(*BRAND_LIGHT)
        self.rect(x, y, w, 22, 'F')
        self.set_fill_color(*color)
        self.rect(x, y, 3, 22, 'F')
        self.set_xy(x + 6, y + 3)
        self.set_font('Helvetica', 'B', 18)
        self.set_text_color(*color)
        self.cell(w - 8, 10, str(value))
        self.set_xy(x + 6, y + 13)
        self.set_font('Helvetica', '', 7)
        self.set_text_color(*BRAND_MID)
        self.cell(w - 8, 6, label.upper())
        self.set_text_color(*BRAND_DARK)


def generate_classroom_report(
    analytics: dict,
    app_name: str = "MamaBird & Chirpy",
    app_domain: str = "threebabybirdies.com",
) -> bytes:
    """Build a one-page class progress report from a classrooms analytics dict."""
    classroom = analytics.get("classroom", {})
    totals = analytics.get("totals", {})
    students = analytics.get("students", [])
    subjects = analytics.get("subject_breakdown", {})

    class_name = classroom.get("name", "Class")
    grade_level = classroom.get("grade_level")
    display_name = f"{class_name}  |  {grade_level}" if grade_level else class_name
    report_date = datetime.utcnow().strftime("%B %d, %Y")

    pdf = ClassroomPDF(class_name=display_name, report_date=report_date, app_name=app_name, app_domain=app_domain)
    pdf.add_page()

    # ── Class Summary ────────────────────────────────────────────
    pdf.section_title("Class Summary")
    card_y = pdf.get_y()
    card_w = 41.5
    gap = 3.5
    x_start = 14
    cards = [
        (str(totals.get("students", 0)),                "Students",         BRAND_BLUE),
        (f"{totals.get('accuracy_pct', 0.0)}%",         "Class Accuracy",   BRAND_GREEN),
        (str(totals.get("sessions", 0)),                "Total Sessions",   BRAND_RED),
        (str(totals.get("badges", 0)),                  "Badges Earned",    (245, 140, 0)),
    ]
    for i, (val, lbl, col) in enumerate(cards):
        pdf.stat_card(x_start + i * (card_w + gap), card_y, card_w, val, lbl, col)
    pdf.set_y(card_y + 28)

    # ── Student Roster ───────────────────────────────────────────
    pdf.section_title("Student Roster")
    if not students:
        pdf.set_font('Helvetica', 'I', 10)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 8, "No students in this class yet.", ln=True)
        pdf.set_text_color(*BRAND_DARK)
    else:
        col_widths = [58, 30, 30, 34, 30]
        headers = ["Student", "Grade", "Sessions", "Accuracy", "Badges"]
        pdf.set_fill_color(*BRAND_BLUE)
        pdf.set_text_color(*WHITE)
        pdf.set_font('Helvetica', 'B', 9)
        for w, h in zip(col_widths, headers):
            pdf.cell(w, 9, h, fill=True, border=0)
        pdf.ln()

        row_fill = False
        for s in students:
            acc = s.get("avg_score", 0.0)
            if acc >= 80:
                acc_color = BRAND_GREEN
            elif acc >= 50:
                acc_color = (180, 140, 0)
            else:
                acc_color = BRAND_RED
            row_y = pdf.get_y()
            if row_fill:
                pdf.set_fill_color(*BRAND_LIGHT)
                pdf.rect(14, row_y, 182, 10, 'F')

            pdf.set_text_color(*BRAND_DARK)
            pdf.set_font('Helvetica', 'B', 10)
            pdf.cell(col_widths[0], 10, str(s.get("child_name", ""))[:26])
            pdf.set_font('Helvetica', '', 10)
            pdf.cell(col_widths[1], 10, str(s.get("grade") or "-"))
            pdf.cell(col_widths[2], 10, str(s.get("sessions", 0)))
            pdf.set_text_color(*acc_color)
            pdf.set_font('Helvetica', 'B', 10)
            pdf.cell(col_widths[3], 10, f"{acc}%")
            pdf.set_text_color(*BRAND_DARK)
            pdf.set_font('Helvetica', '', 10)
            pdf.cell(col_widths[4], 10, str(s.get("badges", 0)))
            pdf.ln(10)
            row_fill = not row_fill

    # ── Subject Breakdown ────────────────────────────────────────
    pdf.section_title("Class Progress by Subject")
    if not subjects:
        pdf.set_font('Helvetica', 'I', 10)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 8, "No subject data recorded yet.", ln=True)
        pdf.set_text_color(*BRAND_DARK)
    else:
        col_widths = [60, 40, 36, 46]
        headers = ["Subject", "Correct / Total", "Accuracy", "Progress"]
        pdf.set_fill_color(*BRAND_BLUE)
        pdf.set_text_color(*WHITE)
        pdf.set_font('Helvetica', 'B', 9)
        for w, h in zip(col_widths, headers):
            pdf.cell(w, 9, h, fill=True, border=0)
        pdf.ln()

        pdf.set_font('Helvetica', '', 10)
        row_fill = False
        for subject, vals in sorted(subjects.items()):
            correct = vals.get("correct", 0)
            total = vals.get("total", 0)
            acc = vals.get("accuracy_pct", 0.0)
            row_y = pdf.get_y()
            if row_fill:
                pdf.set_fill_color(*BRAND_LIGHT)
                pdf.rect(14, row_y, 182, 10, 'F')
            pdf.set_text_color(*BRAND_DARK)
            pdf.set_font('Helvetica', 'B', 10)
            pdf.cell(col_widths[0], 10, subject.title())
            pdf.set_font('Helvetica', '', 10)
            pdf.cell(col_widths[1], 10, f"{correct} / {total}")
            pdf.set_font('Helvetica', 'B', 10)
            pdf.cell(col_widths[2], 10, f"{acc}%")
            bar_x = pdf.get_x()
            bar_y = row_y + 3
            pdf.set_fill_color(220, 220, 220)
            pdf.rect(bar_x, bar_y, 44, 4, 'F')
            fill_w = min(int(acc * 44 / 100), 44)
            pdf.set_fill_color(*BRAND_BLUE)
            if fill_w > 0:
                pdf.rect(bar_x, bar_y, fill_w, 4, 'F')
            pdf.ln(10)
            row_fill = not row_fill

    return bytes(pdf.output())
