from datetime import datetime
from fpdf import FPDF

BRAND_RED    = (204, 41, 41)
BRAND_BLUE   = (110, 180, 212)
BRAND_YELLOW = (245, 194, 0)
BRAND_GREEN  = (74, 139, 63)
BRAND_DARK   = (30, 30, 30)
BRAND_LIGHT  = (249, 249, 249)
BRAND_MID    = (85, 85, 85)
WHITE        = (255, 255, 255)
LIGHT_GREY   = (240, 240, 240)


class ProgressPDF(FPDF):
    def __init__(self, child_name: str, report_date: str):
        super().__init__()
        self.child_name = child_name
        self.report_date = report_date
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        # Red header band
        self.set_fill_color(*BRAND_RED)
        self.rect(0, 0, 210, 38, 'F')
        # Yellow accent line
        self.set_fill_color(*BRAND_YELLOW)
        self.rect(0, 38, 210, 2, 'F')

        self.set_xy(14, 7)
        self.set_text_color(*WHITE)
        self.set_font('Helvetica', 'B', 16)
        self.cell(0, 8, 'MamaBird & Chirpy - Progress Report', ln=True)

        self.set_x(14)
        self.set_font('Helvetica', '', 9)
        self.set_text_color(255, 230, 230)
        self.cell(0, 5, 'AI Educational Chatbot  |  threebabybirdies.com', ln=True)

        self.set_x(14)
        self.set_font('Helvetica', '', 9)
        self.set_text_color(*WHITE)
        self.cell(0, 5, f'Student: {self.child_name}   |   Report Date: {self.report_date}', ln=True)

        self.set_y(48)
        self.set_text_color(*BRAND_DARK)

    def footer(self):
        self.set_y(-18)
        self.set_fill_color(*LIGHT_GREY)
        self.rect(0, self.get_y() - 2, 210, 20, 'F')
        self.set_font('Helvetica', '', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 8, f'Generated by MamaBird & Chirpy  |  {self.report_date}  |  Confidential - For parent/guardian of {self.child_name}', align='C')

    def section_title(self, title: str):
        self.ln(4)
        self.set_font('Helvetica', 'B', 11)
        self.set_text_color(*BRAND_RED)
        self.cell(0, 8, title.upper(), ln=True)
        # Yellow underline
        x, y = self.get_x(), self.get_y()
        self.set_fill_color(*BRAND_YELLOW)
        self.rect(14, y, 182, 1.5, 'F')
        self.ln(5)
        self.set_text_color(*BRAND_DARK)

    def stat_card(self, x: float, y: float, w: float, value: str, label: str, color=None):
        color = color or BRAND_BLUE
        # Card background
        self.set_fill_color(*BRAND_LIGHT)
        self.rect(x, y, w, 22, 'F')
        # Left color stripe
        self.set_fill_color(*color)
        self.rect(x, y, 3, 22, 'F')
        # Value
        self.set_xy(x + 6, y + 3)
        self.set_font('Helvetica', 'B', 18)
        self.set_text_color(*color)
        self.cell(w - 8, 10, str(value))
        # Label
        self.set_xy(x + 6, y + 13)
        self.set_font('Helvetica', '', 7)
        self.set_text_color(*BRAND_MID)
        self.cell(w - 8, 6, label.upper())
        self.set_text_color(*BRAND_DARK)


def generate_progress_pdf(child_data: dict, progress_data: dict, badges: list) -> bytes:
    child_name = child_data.get("child_name", "Student")
    age = child_data.get("age")
    grade = child_data.get("grade")
    report_date = datetime.utcnow().strftime("%B %d, %Y")
    total_sessions = child_data.get("total_sessions", 0)
    streak_days = child_data.get("streak_days", 0)

    total_correct = sum(v.get("correct", 0) for v in progress_data.values())
    total_questions = sum(v.get("total", 0) for v in progress_data.values())
    overall_accuracy = round(total_correct / total_questions * 100, 1) if total_questions else 0.0

    age_grade_parts = []
    if age:
        age_grade_parts.append(f"Age {age}")
    if grade:
        age_grade_parts.append(f"Grade {grade}")
    age_grade_str = "  |  " + "  ·  ".join(age_grade_parts) if age_grade_parts else ""

    pdf = ProgressPDF(child_name=child_name + age_grade_str, report_date=report_date)
    pdf.add_page()

    # ── Overall Summary ──────────────────────────────────────────
    pdf.section_title("Overall Summary")

    card_y = pdf.get_y()
    card_w = 41.5
    gap = 3.5
    x_start = 14
    cards = [
        (f"{overall_accuracy}%", "Overall Accuracy", BRAND_BLUE),
        (str(total_sessions),    "Total Sessions",   BRAND_RED),
        (str(total_questions),   "Questions Answered", BRAND_GREEN),
        (str(streak_days),       "Day Streak",       (245, 140, 0)),
    ]
    for i, (val, lbl, col) in enumerate(cards):
        pdf.stat_card(x_start + i * (card_w + gap), card_y, card_w, val, lbl, col)

    pdf.set_y(card_y + 28)

    # ── Progress by Subject ──────────────────────────────────────
    pdf.section_title("Progress by Subject")

    if not progress_data:
        pdf.set_font('Helvetica', 'I', 10)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 8, "No subject data recorded yet.", ln=True)
        pdf.set_text_color(*BRAND_DARK)
    else:
        # Table header
        col_widths = [60, 40, 36, 46]
        headers = ["Subject", "Correct / Total", "Accuracy", "Progress"]
        pdf.set_fill_color(*BRAND_BLUE)
        pdf.set_text_color(*WHITE)
        pdf.set_font('Helvetica', 'B', 9)
        for w, h in zip(col_widths, headers):
            pdf.cell(w, 9, h, fill=True, border=0)
        pdf.ln()

        pdf.set_font('Helvetica', '', 10)
        row_fill = False
        for subject, vals in sorted(progress_data.items()):
            correct = vals.get("correct", 0)
            total = vals.get("total", 0)
            acc = vals.get("accuracy_pct", 0.0)

            if acc >= 80:
                acc_color = BRAND_GREEN
            elif acc >= 50:
                acc_color = (180, 140, 0)
            else:
                acc_color = BRAND_RED

            row_y = pdf.get_y()
            if row_fill:
                pdf.set_fill_color(*BRAND_LIGHT)
                pdf.rect(14, row_y, 182, 10, 'F')

            pdf.set_text_color(*BRAND_DARK)
            pdf.set_font('Helvetica', 'B', 10)
            pdf.cell(col_widths[0], 10, subject.title())

            pdf.set_font('Helvetica', '', 10)
            pdf.cell(col_widths[1], 10, f"{correct} / {total}")

            pdf.set_text_color(*acc_color)
            pdf.set_font('Helvetica', 'B', 10)
            pdf.cell(col_widths[2], 10, f"{acc}%")

            # Progress bar
            bar_x = pdf.get_x()
            bar_y = row_y + 3
            pdf.set_fill_color(220, 220, 220)
            pdf.rect(bar_x, bar_y, 44, 4, 'F')
            fill_w = min(int(acc * 44 / 100), 44)
            pdf.set_fill_color(*BRAND_BLUE)
            if fill_w > 0:
                pdf.rect(bar_x, bar_y, fill_w, 4, 'F')
            pdf.ln(10)
            pdf.set_text_color(*BRAND_DARK)
            row_fill = not row_fill

    # ── Badges Earned ──────────────────────────────────────────
    pdf.section_title("Badges Earned")

    if not badges:
        pdf.set_font('Helvetica', 'I', 10)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 8, "No badges earned yet - keep learning!", ln=True)
        pdf.set_text_color(*BRAND_DARK)
    else:
        badge_x = 14
        badge_y = pdf.get_y()
        badge_w = 58
        badge_h = 16
        gap_x = 3
        col = 0

        for b in badges:
            name = b.get("badge_name", "Badge")
            earned = b.get("earned_at", "")
            date_str = earned[:10] if earned else ""

            if col == 3:
                col = 0
                badge_x = 14
                badge_y += badge_h + 3

            bx = badge_x + col * (badge_w + gap_x)

            # Badge card
            pdf.set_fill_color(*BRAND_LIGHT)
            pdf.rect(bx, badge_y, badge_w, badge_h, 'F')
            pdf.set_draw_color(*BRAND_YELLOW)
            pdf.rect(bx, badge_y, badge_w, badge_h, 'D')

            pdf.set_xy(bx + 3, badge_y + 3)
            pdf.set_font('Helvetica', 'B', 9)
            pdf.set_text_color(*BRAND_DARK)
            pdf.cell(badge_w - 6, 5, name[:22], ln=False)

            if date_str:
                pdf.set_xy(bx + 3, badge_y + 9)
                pdf.set_font('Helvetica', '', 7)
                pdf.set_text_color(150, 150, 150)
                pdf.cell(badge_w - 6, 4, date_str)

            col += 1
            pdf.set_text_color(*BRAND_DARK)

        pdf.set_y(badge_y + badge_h + 8)

    return bytes(pdf.output())
